FROM ubuntu:18.04
LABEL maintainer="orielh@anyvision.co"

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip \
    python3-dev \
    python3-setuptools \
    vim \
    sudo \
    curl \
    wget \
    libpq-dev \
    net-tools \
    gcc \
    libavdevice-dev \
    pkg-config \
    libsm6 \
    libxext6 \
    libxrender-dev \
    iputils-ping \
    sshpass \
    openssh-client \
    git \
  && ln -s /usr/bin/python3 /usr/local/bin/python \
  && pip3 install --upgrade pip \
  && apt-get clean && apt-get autoremove && rm -rf /var/lib/apt/lists/* \
  && curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - \
  && apt-get install nodejs -y --no-install-recommends \
  && curl -L https://github.com/rancher/rke/releases/download/v1.1.3/rke_linux-amd64 -o /tmp/rke \
  && chmod +x /tmp/rke && mv /tmp/rke /usr/local/bin/


# Set the locale
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

COPY  ./requirements3.txt /tmp/requirements3.txt
RUN pip3 install -r /tmp/requirements3.txt \
  && rm /tmp/requirements3.txt

COPY ./entrypoint.sh environ /
RUN chmod ugo+x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]