---
version: "3.7"
services:
  allocate:
    image: anyvision-hwprovisioner-allocate
    build:
      context: ./hwprovisioner/allocate
      dockerfile: Dockerfile
    volumes:
      - ./hwprovisioner/allocate:/src
    ports:
      - 8080:8080
    environment:
      - REDIS_USER=guest
      - REDIS_PASSWORD=pAssw0Rd!
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis
    working_dir: /src
    command: watchmedo auto-restart --patterns="*.py;*.yaml;*.yml" --recursive -- python -m 'webapp.app' serve
  resourcemanager:
    image: anyvision-hwprovisioner-resourcemanager
    build:
      context: ./hwprovisioner/resourcemanager
      dockerfile: Dockerfile
    volumes:
      - ./hwprovisioner/resourcemanager:/src
    ports:
      - 9080:9080
    environment:
      - REDIS_USER=guest
      - REDIS_PASSWORD=pAssw0Rd!
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - ALLOCATE_API=http://allocate:8080/
      - CONFIG_FILE=${RESOURCES_CONFIG_FILE:-./example.resources.yml}
    depends_on:
      - redis
      - allocate
    working_dir: /src
    command: watchmedo auto-restart --patterns="*.py;*.yaml;*.yml" --recursive -- python -m 'webapp.app' serve
  redis:
    image: redis:5.0.7
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
volumes:
  redis_data:
