FROM ubuntu:18.04
LABEL maintainer="orielh@anyvision.co"

COPY  ./requirements3.txt /tmp/requirements3.txt

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip python3-dev python3-setuptools vim sudo libpq-dev gcc libavdevice-dev pkg-config \
  && ln -s /usr/bin/python3 /usr/local/bin/python \
  && pip3 install --upgrade pip \
  && apt-get clean && apt-get autoremove && rm -rf /var/lib/apt/lists/*

RUN pip3 install -r /tmp/requirements3.txt \
  && rm /tmp/requirements3.txt

COPY ./entrypoint.sh environ /
RUN chmod ugo+x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]
