FROM ubuntu:18.10

RUN  apt update -y && \
     apt install -y python3.7\
     libvirt-daemon python3-libvirt python3-pip\
     sudo pciutils

RUN pip3 install aiohttp munch jinja2

COPY tools/vfio-pci-bind.sh /usr/local/bin/
COPY  * /root/

ENTRYPOINT ["/root/hypervisor"]