.PHONY: packages-install
packages-install:
	apt-get update && apt-get install -y --no-install-recommends \
		python3-pip python3-dev python3-setuptools vim sudo libpq-dev gcc libavdevice-dev pkg-config libsm6 libxext6 libxrender-dev \
		iputils-ping sshpass openssh-client git
	
	pip3 install --upgrade pip
	
	pip3 install -r $(ROOT_DIR)/requirements3.txt 