.PHONY: aws-install
aws-install:

ifeq ($(OS),ubuntu)

	@echo "Installing aws cli on $(OS)"
	sudo apt-get -qq update
	sudo apt-get -q install -y unzip

else ifeq ($(OS),red)

	@echo "Installing aws cli on $(OS)"
	sudo yum install -y unzip

else ifeq ($(OS),centos)

	@echo "Installing aws cli on $(OS)"
	sudo yum install -y unzip

endif

	curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
	unzip -q -o /tmp/awscliv2.zip -d /tmp
	sudo /tmp/aws/install --update
	/usr/local/bin/aws --version


.PHONY: aws-config
aws-config:

# if S3_KEY var not exist get user input 
ifeq ($(S3_KEY),)
	$(eval S3_KEY := $(shell bash -c 'read -e -p "s3 key: " key; echo $$key'))
endif	

# if S3_SECRET var not exist get user input 
ifeq ($(S3_SECRET),)
	$(eval S3_SECRET := $(shell bash -c 'read -e -p "s3 secret: " secret; echo $$secret'))
endif	

# if S3_REGION var not exist get user input 
ifeq ($(S3_REGION),)
	$(eval S3_REGION := "eu-central-1")
endif	

	aws configure set aws_access_key_id $(S3_KEY)
	aws configure set aws_secret_access_key $(S3_SECRET)
	aws configure set default.region $(S3_REGION)