REPOS_DIR ?= $(PARENT_ROOT_DIR)
CLONE_METHOD ?= ssh
GIT_USER ?= ""
GIT_TOKEN ?= ""

.PHONY: git-install
git-install:

ifeq ($(OS),ubuntu)
	@echo "Installing git cli on $(OS)"
	sudo apt-get -qq update
	sudo apt-get -q install -y git
	git --version

else ifeq ($(OS),red)
	@echo "Installing git cli on $(OS)"
	sudo yum install -y git
	git --version

else ifeq ($(OS),centos)
	@echo "Installing git cli on $(OS)"
	sudo yum install -y git
	git --version

endif


.PHONY: git-pull
git-pull:

# if PRODUCT var not exist get user input 
ifeq ($(PRODUCT),)
	$(eval PRODUCT := $(shell bash -c 'read -e -p "PRODUCT: " product; echo $$product'))
endif
	
	while IFS="" read -r line || [ -n "$$line" ]; do \
		case "$$line" in \#*) continue ;; esac ; \
		REPO_NAME=$$(basename $$line | cut -d '.' -f 1) ; \
		if [ ! -d $(REPOS_DIR)/$$REPO_NAME ]; then \
			GIT_REPO_SSH_URL=$$(echo $$line | cut -d ',' -f 1) ; \
			GIT_BRANCH=$$(echo $$line | cut -d ',' -s -f 2) ; \
			if [ $(CLONE_METHOD) = 'url' ]; then \
				if [ -n $(GIT_USER) ] && [ -n $(GIT_TOKEN) ]; then \
					GIT_REPO_URL="https://$(GIT_USER):$(GIT_TOKEN)@github.com/$$( echo $$GIT_REPO_SSH_URL | sed 's/https:\/\/github.com\///' | sed 's/git@github.com://')"; \
				else \
					GIT_REPO_URL="https://github.com/$$( echo $$GIT_REPO_SSH_URL | sed 's/https:\/\/github.com\///' | sed 's/git@github.com://')"; \
				fi ; \
				GIT_REPO_URL_ALIAS="https://github.com/$$( echo $$GIT_REPO_SSH_URL | sed 's/https:\/\/github.com\///' | sed 's/git@github.com://')"; \
			else \
				GIT_REPO_URL="$$GIT_REPO_SSH_URL" ; \
				GIT_REPO_URL_ALIAS="$$GIT_REPO_SSH_URL" ; \
			fi ; \
			if [ -n "$$GIT_BRANCH" ]; then \
				echo "git clone $$REPO_NAME ($$GIT_REPO_URL_ALIAS) on branch $$GIT_BRANCH to $(REPOS_DIR)" ; \
				git -C $(REPOS_DIR) clone $$GIT_REPO_URL -b $$GIT_BRANCH ; \
			else \
				echo "git clone $$REPO_NAME ($$GIT_REPO_URL_ALIAS) to $(REPOS_DIR)" ; \
				git -C $(REPOS_DIR) clone $$GIT_REPO_URL ; \
			fi ; \
		else \
			echo "Git Repository $$REPO_NAME Already exist under $(REPOS_DIR)" ; \
		fi ; \
	done < "$(ROOT_DIR)/dev_environment/$(PRODUCT).txt"