---
openapi: '3.0.0'
info:
  title: AnyVision allocate API
  version: "0.1"
  description: >-
    A service which allocates resources (servers, VMs, devices) for developers
paths:
  # rm.listener.get_jobs jobs / GET
  # rm.listener.volunteer resourcemanager/$rm/ref POST
  # rm.listener.sub jobsws/ / GET (sub)
  # rm.processor.still_free jobs/allocation_id GET
  # rm.processor.processprospect/$rm/ref GET (sub)
  # rm.processor.processprospect/$rm/ref DELETE
  # rm.processor.claim jobqueue/allocation_id POST
  # tester.done jobs/ POST
  # tester.done jobs/allocation_id DELETE

  /claim:
    post:
      tags: [Jobs]
      operationId: webapp.claim.claim
      summary: Adds a job to the queue
      requestBody:
        description: job info
        content:
          application/json:
            schema:
              properties:
                resourcemanager_id:
                  type: string
                  example: "1234"
                inventory_id:
                  type: string
                  example: "1234"
                allocation_id:
                  type: string
                  example: "1234"
      responses:
        200:
          description: Return all items from the inventory
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: integer
                    description: The status for the operation
                    example: 200
  /jobs:
    get:
      tags: [Jobs]
      operationId: webapp.jobs.alljobs
      summary: Get all jobs from the inventory
      responses:
        200:
          description: Return all jobs from the inventory
          content:
            application/json:
              schema:
                type: array
                description: A list of labels associated with this item
                items:
                  type: object
                  properties:
                    allocation_id:
                      type: string
                    data:
                      type: string
    post:
      tags: [Jobs]
      operationId: webapp.jobs.post
      summary: Adds a job to the queue
      requestBody:
        description: job info
        content:
          application/json:
            schema:
              properties:
                demands:
                  type: object
      responses:
        200:
          description: Return all items from the inventory
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: integer
                    description: The status for the operation
                    example: 200
  /ws/jobs:
    get:
      tags: [Jobs, WebSocket]
      operationId: webapp.jobs.sub
      summary: Get all jobs from the inventory
      responses:
        200:
          description: Return all jobs from the inventory
          content:
            application/json:
              schema:
                type: object
                properties:
                  allocation_id:
                    type: string
                  demands:
                    type: string
  /ws/resourcemanager/{resourcemanager_id}/{inventory_id}:
    get:
      tags: [Prospector]
      operationId: webapp.resourcemanager.volunteer_sub
      summary: >-
        websocket for listening to an inventory queue
      parameters:
        - name: resourcemanager_id
          in: path
          description: the rm id
          required: true
          schema:
            type: string
            format: uuid
        - name: inventory_id
          in: path
          description: the inv id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Operation success indicator
          content:
            application/json:
              schema:
                type: object
                properties:
                  allocation_id:
                    type: string
                  demands:
                    type: string
  /resourcemanager/{resourcemanager_id}/{inventory_id}:
    post:
      tags: [Prospector]
      operationId: webapp.resourcemanager.volunteer
      summary: >-
        Allows a resource manager to volunteer one of its resources for a job
      parameters:
        - name: resourcemanager_id
          in: path
          description: the rm id
          required: true
          schema:
            type: string
            format: uuid
        - name: inventory_id
          in: path
          description: the inv id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: job info
        content:
          application/json:
            schema:
              properties:
                match:
                  type: object
      responses:
        200:
          description: Operation success indicator
          content:
            application/json:
              schema:
                type: object
                properties:
                  allocation_id:
                    type: string
                  demands:
                    type: string
  /resourcemanager/{resourcemanager_id}/{inventory_id}/{allocation_id}:
    delete:
      tags: [Prospector]
      operationId: webapp.resourcemanager.volunteer
      summary: >-
        Removes a specific job from the resource list
      parameters:
        - name: resourcemanager_id
          in: path
          description: the rm id
          required: true
          schema:
            type: string
            format: uuid
        - name: inventory_id
          in: path
          description: the inv id
          required: true
          schema:
            type: string
            format: uuid
        - name: allocation_id
          in: path
          description: the allocation id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Operation success indicator
          content:
            application/json:
              schema:
                type: object
                properties:
                  allocation_id:
                    type: string
                  demands:
                    type: string
