---
openapi: '3.0.0'
info:
  title: AnyVision heartbeats API
  version: "0.1"
  description: >-
    A service which extends the reservation of a resource
paths:
  /heartbeat:
    post:
      tags: [Heartbeats]
      operationId: webapp.heartbeats.heartbeat
      summary: Sends a heartbeat for specific allocation id
      requestBody:
        description: allocation id
        content:
          application/json:
            schema:
              properties:
                allocation_id:
                  type: string
                  example: "OFIJAWEOFIJA-WERFWERFWER-WERFWREFW-WRFWERF"
      responses:
        200:
          description: "sucess"
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: integer
                    description: The status for the operation
                    example: 200
